# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Minho Song's hompage
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I am a postdoc working at Sunkyunkwan University.
baseurl: "" # the subpath of the site
url: "https://MinhoSong.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Papers

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: smh3227(at)skku.edu
      link: mailto:smh3227@skku.edu


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
